package com.aura.pc.utils;

import java.util.HashMap;
import java.util.Map;

public class CategoryMapping {
    private static final Map<String, String> CATEGORY_MAP = new HashMap<>();

    static {
        CATEGORY_MAP.put("Bàn - Ghế", "ban-ghe");
        CATEGORY_MAP.put("Gaming Gear", "gaming-gear");
        CATEGORY_MAP.put("Laptop", "laptop");
        CATEGORY_MAP.put("Linh Kiện", "linh-kien");
        CATEGORY_MAP.put("Màn hình", "man-hinh");
        CATEGORY_MAP.put("PC", "pc");
        CATEGORY_MAP.put("Phụ kiện", "phu-kien");
        CATEGORY_MAP.put("ACER | PREDATOR", "laptop-acer");
        CATEGORY_MAP.put("AOC", "man-hinh-aoc");
        CATEGORY_MAP.put("ASUS", "laptop-asus");
        CATEGORY_MAP.put("Asus", "man-hinh-asus");
        CATEGORY_MAP.put("Balo", "balo-tui-xach");
        CATEGORY_MAP.put("Bàn Công Thái Học", "ban-cong-thai-hoc");
        CATEGORY_MAP.put("Bàn Gaming", "ban-gaming");
        CATEGORY_MAP.put("Bàn phím", "ban-phim-may-tinh");
        CATEGORY_MAP.put("CPU", "cpu");
        CATEGORY_MAP.put("Case máy tính", "case-may-tinh");
        CATEGORY_MAP.put("Chuột", "chuot-may-tinh");
        CATEGORY_MAP.put("Dell", "man-hinh-dell");
        CATEGORY_MAP.put("Di động", "man-hinh-di-dong");
        CATEGORY_MAP.put("GIGABYTE | AORUS", "laptop-gigabyte");
        CATEGORY_MAP.put("Gaming", "man-hinh-gaming");
        CATEGORY_MAP.put("Ghế công thái học", "ghe-cong-thai-hoc");
        CATEGORY_MAP.put("Ghế giá tốt", "ghe-gia-tot");
        CATEGORY_MAP.put("Gigabyte", "man-hinh-gigabyte");
        CATEGORY_MAP.put("HDD", "hdd");
        CATEGORY_MAP.put("HP", "laptop-hp");
        CATEGORY_MAP.put("Hi - End", "laptop-hi-end");
        CATEGORY_MAP.put("Koorui", "man-hinh-koorui");
        CATEGORY_MAP.put("LENOVO", "laptop-lenovo");
        CATEGORY_MAP.put("Laptop A.I", "laptop-gaming-ai");
        CATEGORY_MAP.put("Loa", "loa");
        CATEGORY_MAP.put("Lót chuột", "lot-chuot");
        CATEGORY_MAP.put("MSI", "laptop-msi");
        CATEGORY_MAP.put("Mainboard", "mainboard");
        CATEGORY_MAP.put("Microphone", "microphone");
        CATEGORY_MAP.put("Nguồn máy tính", "nguon-psu");
        CATEGORY_MAP.put("PC AI", "pc-gaming-ai");
        CATEGORY_MAP.put("PC Asus", "pc-asus");
        CATEGORY_MAP.put("PC Gigabyte", "pc-gigabyte");
        CATEGORY_MAP.put("PC MSI", "pc-msi");
        CATEGORY_MAP.put("PC gaming", "pc-gaming");
        CATEGORY_MAP.put("PC văn phòng", "pc-van-phong");
        CATEGORY_MAP.put("PC đồ họa", "pc-do-hoa");
        CATEGORY_MAP.put("Philips", "man-hinh-philips");
        CATEGORY_MAP.put("Phụ kiện PC", "phu-kien-pc");
        CATEGORY_MAP.put("Quạt Case", "quat-case");
        CATEGORY_MAP.put("RAM", "ram");
        CATEGORY_MAP.put("SINH VIÊN", "laptop-sinh-vien");
        CATEGORY_MAP.put("SSD", "ssd");
        CATEGORY_MAP.put("Samsung", "man-hinh-samsung");
        CATEGORY_MAP.put("Tai nghe", "tai-nghe-may-tinh");
        CATEGORY_MAP.put("Tay cầm", "tay-cam");
        CATEGORY_MAP.put("Thiết bị mạng", "thiet-bi-mang");
        CATEGORY_MAP.put("Tản nhiệt CPU", "tan-nhiet-cpu");
        CATEGORY_MAP.put("VGA", "vga");
        CATEGORY_MAP.put("Văn phòng", "laptop-van-phong");
        CATEGORY_MAP.put("Webcam", "webcam");
        CATEGORY_MAP.put("Đĩa chơi game", "dia-choi-game");
        CATEGORY_MAP.put("Đồ họa", "man-hinh-do-hoa");
        CATEGORY_MAP.put("1TB - 2TB", "ssd-1tb-2tb");
        CATEGORY_MAP.put("250GB - 256GB", "ssd-250gb-256gb");
        CATEGORY_MAP.put("500GB - 512GB", "ssd-500gb-512gb");
        CATEGORY_MAP.put("A16 Series", "gigabyte-a16-series");
        CATEGORY_MAP.put("ASUS ROG", "rog-series");
        CATEGORY_MAP.put("ASUS RTX 5000 Series", "laptop-asus-rtx-5000-series");
        CATEGORY_MAP.put("Aero", "laptop-gaming-gigabyte-aero");
        CATEGORY_MAP.put("Aorus", "laptop-gaming-gigabyte-aorus");
        CATEGORY_MAP.put("Aspire", "aspire");
        CATEGORY_MAP.put("CPU AMD", "cpu-amd");
        CATEGORY_MAP.put("CPU Intel", "cpu-intel");
        CATEGORY_MAP.put("Case Asus", "case-asus");
        CATEGORY_MAP.put("Case Cooler Master", "case-cooler-master");
        CATEGORY_MAP.put("Case Corsair", "case-corsair");
        CATEGORY_MAP.put("Case Deepcool", "case-deepcool");
        CATEGORY_MAP.put("Case Gigabyte", "case-gigabyte");
        CATEGORY_MAP.put("Case HYTE", "case-hyte");
        CATEGORY_MAP.put("Case MIK", "case-mik");
        CATEGORY_MAP.put("Case MSI", "case-msi");
        CATEGORY_MAP.put("Case NZXT", "case-nzxt");
        CATEGORY_MAP.put("Case Xigmatek", "case-xigmatek");
        CATEGORY_MAP.put("Creator", "laptop-gaming-msi-creator");
        CATEGORY_MAP.put("Crosshair | Vector", "laptop-msi-crosshair-pulse-gp-series");
        CATEGORY_MAP.put("Cyborg / Thin GF", "laptop-msi-cyborg-thin-gf-series");
        CATEGORY_MAP.put("Gigabyte RTX 5000", "laptop-gigabyte-rtx-5000-series");
        CATEGORY_MAP.put("HDD Laptop", "hdd-laptop");
        CATEGORY_MAP.put("HDD PC", "hdd-pc");
        CATEGORY_MAP.put("HP RTX 5000 Series", "laptop-hp-rtx-5000-series");
        CATEGORY_MAP.put("Helios", "helios");
        CATEGORY_MAP.put("LOQ Series", "loq-series");
        CATEGORY_MAP.put("Legion", "legion-gaming");
        CATEGORY_MAP.put("MSI RTX 5000", "laptop-msi-rtx-5000-series");
        CATEGORY_MAP.put("Mainboard Asus", "mainboard-asus");
        CATEGORY_MAP.put("Mainboard Gigabyte", "mainboard-gigabyte");
        CATEGORY_MAP.put("Mainboard MSI", "mainboard-msi");
        CATEGORY_MAP.put("Nguồn Asus", "nguon-asus");
        CATEGORY_MAP.put("Nguồn Cooler Master", "nguon-cooler-master");
        CATEGORY_MAP.put("Nguồn Corsair", "nguon-corsair");
        CATEGORY_MAP.put("Nguồn Deepcool", "nguon-deepcool");
        CATEGORY_MAP.put("Nguồn Gigabyte", "nguon-gigabyte");
        CATEGORY_MAP.put("Nguồn MSI", "nguon-msi");
        CATEGORY_MAP.put("Nitro", "nitro-5");
        CATEGORY_MAP.put("Omen", "omen");
        CATEGORY_MAP.put("Quạt Deepcool", "quat-deepcool");
        CATEGORY_MAP.put("Quạt Xigmatek", "quat-xigmatek");
        CATEGORY_MAP.put("RAM Laptop", "ram-laptop");
        CATEGORY_MAP.put("RAM PC", "ram-pc");
        CATEGORY_MAP.put("Raider GE", "laptop-msi-ge-series");
        CATEGORY_MAP.put("Stealth GS", "laptop-msi-gs-series");
        CATEGORY_MAP.put("Sword / Katana", "laptop-msi-sword-katana-series");
        CATEGORY_MAP.put("TUF Series", "tuf-series");
        CATEGORY_MAP.put("Titan", "laptop-msi-gt-series");
        CATEGORY_MAP.put("Tản nhiệt Asus", "tan-nhiet-asus");
        CATEGORY_MAP.put("Tản nhiệt Cooler Master", "tan-nhiet-cooler-master");
        CATEGORY_MAP.put("Tản nhiệt Corsair", "tan-nhiet-corsair");
        CATEGORY_MAP.put("Tản nhiệt Deepcool", "tan-nhiet-deepcool");
        CATEGORY_MAP.put("Tản nhiệt Gigabyte", "tan-nhiet-gigabyte");
        CATEGORY_MAP.put("Tản nhiệt MSI", "tan-nhiet-msi");
        CATEGORY_MAP.put("Victus", "laptop-gaming-hp-victus");
        CATEGORY_MAP.put("Vivobook", "vivobook");
        CATEGORY_MAP.put("Ổ cứng di động", "o-cung-di-dong");
        CATEGORY_MAP.put("Mainboard AMD", "mainboard-msi-amd");
        CATEGORY_MAP.put("Mainboard Intel", "mainboard-gigabyte-intel");
        CATEGORY_MAP.put("Mainboard X870", "mainboard-gigabyte-x870");
        CATEGORY_MAP.put("Mainboard Z890 Series", "mainboard-z890-gigabyte-series");
        CATEGORY_MAP.put("RAM Corsair", "ram-corsair");
        CATEGORY_MAP.put("RAM G.skill", "ram-g-skill");
        CATEGORY_MAP.put("RAM Kingston", "ram-kingston");
        CATEGORY_MAP.put("RAM TeamGroup", "ram-teamgroup");
        CATEGORY_MAP.put("ROG Flow", "flow");
        CATEGORY_MAP.put("ROG Strix G", "strix-g");
        CATEGORY_MAP.put("ROG Zephyrus", "zephyrus");
        CATEGORY_MAP.put("Scar", "scar");
        CATEGORY_MAP.put("Vivobook Gaming", "asus-v16-gaming-creator");
        CATEGORY_MAP.put("Vivobook văn phòng", "laptop-van-phong");
    }

    public static String getSlug(String name) {
        return CATEGORY_MAP.getOrDefault(name, null);
    }
}
